### ISSUE TITLE
remove the non-squirrel ship reference.  

### ISSUE THREAD

**Issue by gbinal** [18F/18f-bot#10]
Folks are always sad when the `ship it` image that comes back is a ship not a squirrel.  

http://gifs.gifbin.com/092010/1285616410_ship-launch-floods-street.gif should be removed from the list of images.  

Granted, not the most important thing, but if easy to cut out, pretty please.

**Comment by afeld** [comment]
Feel free to PR the original!

https://github.com/github/hubot-scripts/blob/a084e64aca8440695630230c71e59ea76094403d/src/scripts/shipit.coffee#L19-L35

**Comment by gbinal** [comment]
Thanks!  

https://github.com/github/hubot-scripts/pull/1633
