### ISSUE TITLE
x-post into private channels?

### ISSUE THREAD

**Issue by mgwalker** [18F/18f-bot#121]
Should the bot be able to crosspost into private channels?  For good reason, it isn't allowed to crosspost *from* private channels (risk of accidentally sharing something that shouldn't be shared), but what arguments might there be against crossposting *into* private channels?

It's possible it could crosspost into private channels before and that stopped working when I added the channel membership checks (the APIs for checking public and private channels are different, because *reasons*).  I have a branch (`xpost-to-private-channels`) that adds this functionality again, but I didn't want to create a PR for it and have someone merge it without a discussion first of whether that is something we want.

Thoughts?

**Comment by afeld** [comment]
I would guess that it still works - the bot just needs to be in the channel already.

**Comment by mgwalker** [comment]
Nah, it doesn't work right now.  Before it attempts to xpost, it checks if it's in the target channel, but it only queries the `channels.list` API, which doesn't report any private channels.  So if you try to xpost to a private channel, it will say that it isn't in that channel.

**Comment by mgwalker** [comment]
Closed by #168 (from #164)
