### ISSUE TITLE
fix tests

### ISSUE THREAD

**Issue by afeld** [18F/18f-bot#130]
Possibly related to #126.

**Comment by mgwalker** [comment]
In the short term, I made a bandaid fix in #129.  The problem with the love-script tests is that the Hubot test harness had a breaking update in the compatible version range.  We rely on `^1.5.1`, but the breaking change was introduced in `1.9.0`, which is compatible with our specified range.  My temporary fix was to restrict our range to `~1.5.1`.  That's faster than updating the dependencies and fixing the tests, and...  well, y'know, time is precious and all that.  ☹️

**Comment by afeld** [comment]
Mind splitting that out to it's own pull request?

**Comment by mgwalker** [comment]
#140 bumped the test harness to 1.9.0 and everything is working.  I don't remember the details of the break, but I guess we're good now?
