### ISSUE TITLE
Consider removing XPOST

### ISSUE THREAD

**Issue by ertzeid** [18F/18f-bot#164]
Slack now supports this, and frankly Slack's version is prettier and probably works better. Also, Slack's version doesn't raise questions like "what if single-channel guests (cough #alumni cough) xpost into other channels?" whereas we've had to remove Charlie from some channels specifically for this reason.

**Comment by mgwalker** [comment]
One thing xpost allows that Slack's version doesn't is the ability to post into a channel without joining it.  I've used it for that purpose a couple of times.  That said, leaving a channel afterwards isn't a heavy lift.  😛

#121 is about whether or not xpost should be allowed to post into private channels.  Previously we had a discussion about whether it should allow xposts _*from*_ private channels (we landed on "no," then switched to "yes").  So I agree, maintaining this ourselves makes us think a lot about what kinds of message sharing we should allow.  Maybe that flexibility is worth it, maybe not.

**Comment by mgwalker** [comment]
Decision coming COB **Thursday, May 2**.

**Comment by mogul** [comment]
Has anyone done a search In Slack to see how heavily and frequently the feature is (ab)used currently?

**Comment by mgwalker** [comment]
I've informally scanned the search results.  It's not used a lot - most results for "xpost" are someone announcing that they are cross-posting, not using Charlie.

**Comment by gbinal** [comment]
:shrugs: I'm fine killing it just to simplify things.
