### ISSUE TITLE
fix `hug me`

### ISSUE THREAD

**Issue by afeld** [18F/18f-bot#24]
Switching to the AWS SDK in #22 broke it.

> **me:** charlie hug bomb
> **charlie:** aidanfeldman: Error retrieving images: TimeoutError: Missing credentials in config

I didn't catch it because I tested locally, and it was presumably reading my local credentials.

**Comment by mogul** [comment]
@dlapiduz wanted this assigned to him

**Comment by dlapiduz** [comment]
creds for s3 were missing. it is good now.
