### ISSUE TITLE
Bot doesn't like channel names with - in them

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#27]
cc @ertzeid and @goodnightjj , I bet we can figure this one out without Aiden.

**Comment by wslack** [comment]
Not unsure about this.

**Comment by wslack** [comment]
This was fixed by realizing that charlie happens to not be in most channels with hyphens that I tested.

**Comment by afeld** [comment]
STUPID COMPUTERS

:wink:

**Comment by wslack** [comment]
PEBCAK
