### ISSUE TITLE
XPOST Script: Charlie doesn't know a message isn't XPOST'd

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#30]
https://github.com/18F/18f-bot/blob/master/scripts/xpost.coffee doesn't let the user know when there's been an issue posting to another channel.

**Comment by wslack** [comment]
Ome hting to figure out - how does Charlie know which channels Charlie is in? Is there a test for that?

**Comment by mgwalker** [comment]
Fixed by #100
