### ISSUE TITLE
XPOST Script: doesn't fire on iOS

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#31]
It works on Android and Desktop but not iOS. Other scripts do fire, so it might be something in the encoding? Unsure.

**Comment by afeld** [comment]
We ended talking a bit about it over Hangout, but my hypothesis is that it's because the message format for channel names is different in iOS, relative to the other platforms (strangely). Relevant info:

https://api.slack.com/docs/formatting

**Comment by mgwalker** [comment]
Fixed by some combination of #89, #93, and #99.
