### ISSUE TITLE
XPOST Script: Desire to post a message to multiple channels

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#34]
XPOST #DC #SF #etc should post a message to three channels. It's been tried organically by at least one user already. [edit: now at least two]

Note: will require new and more complex parsing coding.

**Comment by wslack** [comment]
SO post about this: http://stackoverflow.com/questions/33599499/how-do-i-identify-a-string-fragment-then-parse-fragment-into-variable-size-array

**Comment by mgwalker** [comment]
Will work on this one after #116 is merged, since it modifies how the message is parsed.
