### ISSUE TITLE
XPOST Script: Detect failed XPOST command and post instructions.

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#36]
A user said "XPOST to #channel-name," which isn't the pattern were looking for, but makes me think we should detect the language "xpost" and fire instructions when there's no detected channels in the message.

**Comment by wslack** [comment]
Another pattern to check for is #xpost #channelname

**Comment by mgwalker** [comment]
I should have documented _why_, but I recall from #99 that the hash before the channel name is absolutely required.  I think it's because the Hubot Slack adapter started returning channel IDs instead of names in the code, and the only way to get the ID is with the hash.
