### ISSUE TITLE
Create "invite to cloud.gov <email>" command

### ISSUE THREAD

**Issue by dlapiduz** [18F/18f-bot#37]
Here is the UAA endpoint https://github.com/cloudfoundry/uaa/blob/master/docs/UAA-APIs.rst#inviting-users

**Comment by rogeruiz** [comment]
We now have self-service account creation for :cloud:.gov, so we can safely close this.
> https://cloud.gov/docs/getting-started/accounts/#to-get-access-to-cloud-gov

**Comment by mgwalker** [comment]
cloud.gov now has self-service account creation.  See https://cloud.gov/docs/getting-started/accounts/#to-get-access-to-cloud-gov
