### ISSUE TITLE
Deployment questions from 18F/hubot-slack-github-issues

### ISSUE THREAD

**Issue by mbland** [18F/18f-bot#38]
I've got a few questions from 18F/hubot-slack-github-issues#4, plus one I forgot to mention there:

- What is the feasibility of deploying a `config.json` to production without checking it directly into 18F/18f-bot?
  - Should I extract the GitHub token as an env var and check the rest of the `config.json` into this repo instead?
- How comfortable would y'all be switching 18F/18f-bot to an 18F fork of hubot-slack to support `reaction_added` messages before that support is added upstream? (As noted in 18F/hubot-slack-github-issues#4, I'm going to ping slackhq about this, too.)
- The current Node.js engine in `package.json` is `0.10.x`. Is that what's actually running in production? I'm using features that aren't supported until 4.2. Any chance for an upgrade?

Happy to discuss either in this issue or that one, or to set up a Hangout or something to chat in real-time.

**Comment by afeld** [comment]
> What is the feasibility of deploying a config.json to production without checking it directly into 18F/18f-bot?

See https://github.com/18F/hubot-slack-github-issues/pull/4#issuecomment-164501246.

> Should I extract the GitHub token as an env var and check the rest of the config.json into this repo instead?

Yes please!

> How comfortable would y'all be switching 18F/18f-bot to an 18F fork of hubot-slack to support reaction_added messages before that support is added upstream?

As long as we make a note about the reason, :+1:

> The current Node.js engine in package.json is 0.10.x. Is that what's actually running in production?

Yep – [the Node buildpack should respect that](https://github.com/cloudfoundry/nodejs-buildpack#specify-a-node-version).

> Any chance for an upgrade?

I think our version of `hubot` may require 10.x, but that's probably due for an upgrade as well. :+1:

**Comment by mbland** [comment]
Our [18F/hubot-slack-github-issues Hubot plugin](https://github.com/18F/hubot-slack-github-issues/) is now running successfully as a [npm package](https://www.npmjs.com/package/hubot-slack-github-issues) as of #42 (and #43). Thanks for all the help, @afeld!
