### ISSUE TITLE
Clean up log output

### ISSUE THREAD

**Issue by mbland** [18F/18f-bot#44]
So I'm trying to figure out why [hubot-slack-github-issues](https://github.com/18F/hubot-slack-github-issues) didn't post the link to 18F/handbook#426 back into the channel, but since CloudFoundry seems to keep a limited amount of logs, the hubot-slack-github-issues log messages have been drowned out by a lot of:

```
OUT [Wed Dec 30 2015 14:35:04 GMT+0000 (UTC)] DEBUG Executing listener callback for Message '[object Object]'
OUT node_redis: no callback to send error: OOM command not allowed when used memory > 'maxmemory'.
OUT [Wed Dec 30 2015 14:35:08 GMT+0000 (UTC)] ERROR Error: OOM command not allowed when used memory > 'maxmemory'.
[...stack trace...]
```

and

```
[Wed Dec 30 2015 14:35:08 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'length' of undefined
OUT   at Object.<anonymous> (/home/vcap/app/node_modules/hubot-cf-notifications/src/event_checker.coffee:37:21, <js>:44:39)
```

Any chance we can get these tidied up soon?

**Comment by afeld** [comment]
I don't think I can dedicate time to doing so any time soon, but if you want to, go for it :wink:

**Comment by mbland** [comment]
We'll see how bored I get over the weekend. ;-)

**Comment by afeld** [comment]
The former may be #55, and the latter is one or both of:

* [the Cloud Foundry API](https://apidocs.cloudfoundry.org/229/events/list_all_events.html) response format changed
* the Cloud Foundry `hubot-cf-listener` user password needs to be reset (and for some reason I can't seem to find the email it was registered with)

**Comment by mgwalker** [comment]
This seems to have been fixed by someone setting the `HUBOT_LOG_LEVEL` env var to `error`.
