### ISSUE TITLE
a youtube error

### ISSUE THREAD

**Issue by gbinal** [18F/18f-bot#45]
A `charlie youtube ____` request generated this error:  _You must configure the HUBOT_YOUTUBE_API_KEY environment variable_.

Example at 
https://18f.slack.com/archives/general-talk/p1450728971005086

**Comment by mgwalker** [comment]
Should we remove this script from Charlie?  I don't know if we had/have an 18F youtube API key or if it was someone's personal key.  Either way, are there any potential compliance problems with having a bot post random youtube links into slack?

**Comment by afeld** [comment]
Feel free to remove.
