### ISSUE TITLE
Documentation tagging bot in DMs

### ISSUE THREAD

**Issue by annahsebok** [18F/18f-bot#52]
Would be great if the documentation tagging bot could file issues on items flagged in DMs, not just in channels.

**Comment by afeld** [comment]
I'm not sure that we would want to have the bots have access to DMs, because that would give them all sorts of other privileges that we probably don't want them to have. Closing for now, but feel free to reopen if you feel strongly about it or others have ideas here.

**Comment by annahsebok** [comment]
@afeld I actually opened this issue by suggestion of @mbland. I'm not suggesting bots have access to all the things, solely that if I :koala: something in a DM with somebody, an issue would get opened for the product guide. I presume this would be helpful for any documentation bot. I'm not sure how we could only offer this without opening up other privileges, but I'd like to reopen and see if @mbland has any ideas.

**Comment by mbland** [comment]
So at the moment I don't _think_ there's support for [`reaction_added` messages](https://api.slack.com/events/reaction_added) in DMs. That said, I haven't looked at the code, haven't looked at actual incoming data for DM reaction events, and I've already pinged Slack to update their API docs (which they have). When I get time, probably next week, I'm happy to look into it.

**Comment by afeld** [comment]
Right – what I'm saying is that for a bot to be able to access anyone's DMs, it would probably be necessary to have Noah-level admin powers (if it's even possible at all through the API), which is probably not access we want to give anyone that has access to Hubot on the backend.

**Comment by mbland** [comment]
Yeah, I see what you're saying. I was wondering whether it was even possible, but I agree, I'm not certain we'd want to do it even if it is.

**Comment by annahsebok** [comment]
I defer to your wonderful people as to what makes the most sense and is feasible. Just wanted to make sure it was considered.

**Comment by mgwalker** [comment]
The Slack RTM API (which Charlie uses) can only access DMs that it is a party to, so in order for this to work, you'd have to invite Charlie into the DM and then add the emoji reaction.  Amusingly, I authored a PR a little while back to have the plugin we use ([mbland/slack-github-issues](https://github.com/mbland/slack-github-issues/)) explicitly [ignore direct messages](https://github.com/mbland/slack-github-issues/pull/3).

Going to close this one  :)
