### ISSUE TITLE
Charlie runs out of memory a lot, may explain flakiness

### ISSUE THREAD

**Issue by mogul** [18F/18f-bot#55]
Now that we’ve got logs.cloud.gov up, we can see that Charlie logs errors  3-4x more than any other app on cloud.gov. It looks like it’s due to running out of memory a lot, and I guess we’ve seen that it’s flaky in Slack sometimes… @dlapiduz said 

> it is redis
> we need to move to use our redis service
> rather than IBMs
> (yes that is happening)

I'm not sure who looks after that, but in any case I'm capturing that there's a problem to be solved here per conversation in #bots.

**Comment by mgwalker** [comment]
Not sure if this is still an issue.  Charlie seems to have been pretty stable for a while now.  I want to add a startup response where it posts into #bots so we can see if it's still restarting frequently and we just don't see it anymore.  If we get a few weeks without anything, maybe we can close this one?

**Comment by afeld** [comment]
Sounds good. We can reopen if needed. https://github.com/cloudfoundry/nodejs-buildpack/pull/82 may help, too.
