### ISSUE TITLE
add a Handbook search script

### ISSUE THREAD

**Issue by afeld** [18F/18f-bot#6]
> As a user, I want to be able to search Hub documentation from the warm embrace of Slack.

Possible that the search code from the Hub could be extracted to a Node module and shared by both the Hub and Hubot.

/cc @melodykramer @ultrasaurus

**Comment by arowla** [comment]
+1

**Comment by afeld** [comment]
@monfresh just [mentioned](https://18f.slack.com/archives/random/p1430499833001859) https://github.com/gleitz/howdoi as a related thing...pretty cool.

**Comment by afeld** [comment]
The idea also came up in Slack to be able to ask "what is X", and be able to pull from a list somewhere. We're using Slackbot responses for some things right now ("guest wifi", "what's an ATO", etc.), but might be nice to have that information shared with the Hub. Maybe a data file for https://hub.18f.gov/private/acronyms/, which a Hubot script could pull from?

**Comment by catherinedevlin** [comment]
If we get it working *really* well, a bot could try to detect questions posted in slack and respond with a search result.

**Comment by mtorres253** [comment]
Love that suggestion @catherinedevlin

**Comment by mbland** [comment]
It may be possible to extend [18F/hubot-slack-github-issues](https://github.com/18F/hubot-slack-github-issues/) with this capability once @catherinedevlin, @andrewmaier, and I take a pass at revamping search in [18F/hub](https://github.com/18F/hub) (which we're doing right now, actually).

**Comment by mbland** [comment]
I should mention, that's in the context of using the :evergreen_tree: and other emoji tagging, and doing a search instead of filing an issue. It's possible we could set a threshold whereby if a tagged message gets fewer than X results with score above Y, it files an issue; otherwise it posts links to the results with a score above Y.

**Comment by afeld** [comment]
Related: https://github.com/FeelTrainCoop/101atron via @melodykramer.

**Comment by mgwalker** [comment]
Is this still relevant?

**Comment by afeld** [comment]
Changed Hub->Handbook
