### ISSUE TITLE
Charlie should auto-DM someone who got a :check: on their message

### ISSUE THREAD

**Issue by wslack** [18F/18f-bot#69]
This would allow people reporting that a task was done to not have to take up channel space with a "@person - done!" In order to make them aware their ask was handled.

The bot should also auto-append another emoji - maybe :hubot: to signal the DM was sent.

**Comment by mgwalker** [comment]
This seems like it could be a little annoying when people use :check: for other things, like just agreement or acknowledgement.  It might also contribute to a situation @waldoj has remarked on before, where we have lots of hidden norms, which makes onboarding weird.  Thoughts?

**Comment by wslack** [comment]
yeah, I think it would need to be more narrowly scoped

**Comment by mgwalker** [comment]
Maybe it could be configured on a per-channel basis.  So throwing a check on someone's message in a channel where people routinely ask for things (like #admins-github) would have Charlie DM them, but generally Charlie would ignore the checkmark.
