### ISSUE TITLE
Bot support for Q&A sessions

### ISSUE THREAD

**Issue by rdpiazza** [18F/18f-bot#70]
As a moderator of a Q&A session with an associated Slack channel, I want to be able to quickly find all questions asked in that Slack channel (as opposed to meta-discussions, comments on audio quality, reaction GIFs), so that I can make sure all questions get asked of the speaker. 

Implementation idea: flag questions using an emoji, similar to Koala or Evergreen bots?  Do something with the emoji'd questions?  But don't put them in Github, please.

**Comment by mgwalker** [comment]
Thinking through how this might work.  This is kind of what I'm imagining right now, what do you think @rdpiazza?

>**User:** charlie take questions
>
>**Charlie:** Okay, I'm now gathering questions and adding them to a thread attached to this message.  To add a question, start a message with the ❓ emoji, or add a ❓ emoji reaction to a message.
>
> **User 2:** ❓ How does that thing they're saying affect that other thing I care about?
>
> *Charlie adds the question to the thread, adds a :hubot: emoji reaction to the question*

**Comment by rdpiazza** [comment]
Oh interesting to see this revived! I feel that we've found an alternative effective way of managing this now by using a linked Google Doc, rather than sourcing questions in Slack. I'd be happy with closing this request as No Fix Needed/Overtaken By Events.
