### ISSUE TITLE
As a user of public and private channels, I'd like the evergreen bot to produce useful an error message when i attempt to use it in a private channel.

### ISSUE THREAD

**Issue by nicoleslaw** [18F/18f-bot#72]
From @onezerojeremy: https://github.com/18F/handbook/issues/830

Not sure if this should go here, but instead of this: 
![screen shot 2016-04-22 at 1 37 24 pm](https://cloud.githubusercontent.com/assets/474916/14749775/6e722d0e-088f-11e6-9065-4d77370aa0b0.png)

perhaps the error message could indicate that "Sorry, evergreen bot doesn't work in private channels". 

Apologies if this is the wrong place to submit this issue, or if this is already noted elsewhere, or if it's just impossible.

**Comment by stvnrlly** [comment]
Not to re-redirect the issue, but the evergreen script is powered by https://github.com/18F/hubot-slack-github-issues. It might make sense to have the issue in both places and link them, as I don't know who's maintaining the plugin right now.

**Comment by mgwalker** [comment]
Need to revisit this.  @mbland forked and is now primary maintainer of the [hubot-slack-github-issues](https://github.com/mbland/hubot-slack-github-issues) plugin, and I believe we coordinated with him a while back on exactly this.  I'll double-check!

**Comment by mgwalker** [comment]
Resolved by mbland/slack-github-issues#4 (see 18f/handbook#373 for example, which was created from an 🌲 reaction in a private channel)
